title: Lernjournal Bibliotheks- und Archivinformatik
author: Kerstin
email: kerstin.schneider@stud.fhgr.ch
description: > # this means to ignore newlines
 Lerntagebuch zum Modul Bibliotheks- und Archivinformatik HS21

# social links
twitter_username:  # DO NOT include the @ character, or else the build will fail!
github_username:  Elekena # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
